.TH microtrans 3 "December 27, 2017" "" "microtrans"

.SH НАЗВАНИЕ
microtrans \- миниатюрный консольный переводчик, использующий сервис Яндекс.Переводчик

.SH СИНТАКСИС
.B microtrans.py [-l=языковой_режим -k=ключ или -K=файл_ключа] [-vdhq] [--help --version]
.br

.SH ОПИСАНИЕ
Опции:
.RS 4
-h или --help - вывести справку
.RE
.RS 4
-v или --version - вывести информацию о версии
.RE
.RS 4
-q - подавляет дополнительную информацию
.RE
.RS 4
-l - установить режим перевода в виде 'en-ru', 'de-en'  и т.д. По умолчанию используется en-ru
.RE
.RS 4
-d - диалоговый режим
.RE
.RS 4
-k - задать ключ сервиса Яндекс.Переводчик в командной строке
.RE
.RS 4
-K - задать ключ сервиса Яндекс.Переводчик в указанном файле
.RE

.SH КОДЫ ВОЗВРАТА
.RS 4
0 в случае успешного выполнения и 1 в случае ошибки
.RE

.SH ПРИМЕЧАНИЯ
.RS 4
Во избежания коллизий, связанных с лицензионными ограничениями
на используемый ключ, крайне желательно пользоваться собственным ключом,
.RE
.RS 4
который можно бесплатно получить на портале Яндекс.
Все замечания присылать по адресу <tyukalov@bk.ru>
.RE

.SH ОШИБКИ
.RS 4
В некоторых системах (обнаружено Windows XP) и при некоторых настройках локали
выдаёт ошибку при выводе результата. На данный момент реализована обработка
этой исключительной ситуации, заключающаяся в выводе сообщения вида:
"Error! There may be an issue with the unsupported character set"
.RE


